Strict dependencies check for aiida-core
aiidalab/aiidalab-home pull request #128
Opened 2023-02-07 14:46 UTC by unkcpz

fixes https://github.com/aiidalab/aiidalab/issues/318

The compatibilities only checked for the installed app. If the user going to install the app that would potentially override the aiida-core version the installation will fail in AppManager but the user is not notified before they trigger the installation procedure. 
In this PR, the check for the to-be-installed app is activated when the version is selected and will block the user to install the app that has incompatible "core" dependencies. The "core" dependencies now are only `aiida-core`.
The method `_check_strict_dependency` is used to check that the `aiida-core` version of the container is not overridden by the app. 

If the "core" dependencies are not incompatible, the dependencies to be installed or updated will show in the info notes to remind the user what will be overridden.

2023-02-07 15:44 UTC, unkcpz commented
To test with this PR, you can clone the repo and ln the `/home/jovyan/app/home` to the new folder.

2023-02-07 19:47 UTC, danielhollas requested changes
Hi @unkcpz, this is great, thanks for working on this. I did not test yet, for now just a couple of clarifying questions and some suggestions for variable names.

1. Does this mean that no changes are needed in the `aiidalab` repo? 
2. Will this also allow us to solve the spurious "Update available", if the new version is incompatible? Perhaps that's for a follow up PR?
3. We will need to backport this to the old docker stack image. We need to find out if the current `aiidalab-home` is still compatible or if there were any breaking changes in the meantime.

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +        for requriment in unmatched_requirements:
typo, needs to be fixed below as well
```suggestion
        for requirement in unmatched_requirements:
```

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +        dependencies = []
Clearer naming?
```suggestion
        dependencies_to_install = []
```

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +            if "aiida-core" in dep.installed:
Please generalize this code for the future, define a list of strict dependencies as a global constant (probably at the top of the file or somwhere).

I also wonder, should this function be here or rather in `aiidalab` repo? I don't have an answer now, but something to think about.

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +            strict_dependency = self._check_strict_dependencies(dependencies)
```suggestion
            strict_dependency_violation = self._check_strict_dependencies(dependencies)
```
or maybe
```suggestion
            violates_strict_dependency = self._check_strict_dependencies(dependencies)
```

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +            dependencies = self.find_to_be_installed_dependencies(
```suggestion
            dependencies_to_install = self.find_to_be_installed_dependencies(
```

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +                        dependencies=dependencies,
```suggestion
                        dependencies=dependencies_to_install,
```

2023-02-07 19:47 UTC, danielhollas commented on home/app_manager.py
> +            {% for p in dependencies %}
```suggestion
            {% for p in dependencies_to_install %}
```

2023-02-08 11:27 UTC, unkcpz commented
I address the variables naming suggested by @danielhollas and close this one with replaced it by #130.

2023-02-08 11:27 UTC, closed without merging