Start page: use `ipw.VBox` instead of `ipw.Output` to display apps.
aiidalab/aiidalab-home pull request #185
Opened 2024-11-22 12:46 UTC by yakutovicha

This also allows to remove hotfix to observe collapsing apps.

2024-11-28 17:56 UTC, danielhollas requested changes
Looks great, thank you for this cleanup @yakutovicha! My only request is to delete the now unused workaround decorator.

I think this change conflicts with #184 since it touches the same code, I think it would be good to merge this one first, since it might simplify the implementation in #184. CC @edan-bainglass d

2024-11-28 17:56 UTC, danielhollas commented on home/start_page.py
> -    @_workaround_property_lock_issue
Great! Please remove this decorator (defined in this file) since it is not used anywhere else.

2024-12-02 13:10 UTC, danielhollas approved these changes

2024-12-02 14:06 UTC, merged

2024-12-03 08:57 UTC, edan-bainglass commented
@yakutovicha very nice! @danielhollas thanks for the ping. I'll rebase and adjust/clean up.